name: trial
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_spinkit: ^5.1.0
  responsive_framework: ^0.2.0
  google_fonts: ^4.0.3
  easy_scroll_animation: ^1.0.2
  delayed_display: ^2.0.0
  reveal_on_scroll: ^0.0.3
  parallax_animation: ^0.0.3
  # lazy_loading_list: ^1.0.1
  custom_refresh_indicator: ^2.0.1
  font_awesome_flutter: ^10.4.0
  flutter_staggered_grid_view: ^0.6.2
  anim_search_bar: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
